add release script and update circleCI config to use workflows

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,20 +22,27 @@ jobs:
             - ./node_modules
           key: dependencies-{{ checksum "package.json" }}
 
-      - run:
-          name: Deploy
+  publish:
+    working_directory: ~/cumulus-message-adapter
+    steps:
+      - publish_release:
+          name: Publish release
           command: |
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              cd ~/cumulus-message-adapter
+            GITHUB_TOKEN=${GITHUB_TOKEN} sh bin/release.sh
+      - publish_npm:
+          name: Publish to NPM
+          command: |
+            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
+            npm publish || echo 'npm publishing failed'
 
-              export VERSION=$(jq --raw-output .version package.json)
-              curl -H \
-                "Authorization: token $GITHUB_TOKEN" \
-                -d "{\"tag_name\": \"v$VERSION\", \"target_commitsh\": \"v$VERSION\", \"name\": \"v$VERSION\"}" \
-                -H "Content-Type: application/json" \
-                -X POST \
-                https://api.github.com/repos/nasa/cumulus-message-adapter-js/releases |grep \"url\" |grep releases |sed -e 's/.*\(https.*\)\"\,/\1/'| sed -e 's/api/uploads/'
-
-              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
-              npm publish || echo 'npm publishing failed'
-            fi
+workflows:
+  version: 2
+  build:
+    jobs:
+      - build
+  publish:
+    jobs:
+      - publish
+          filters:
+            branches:
+              only: master
