CUMULUS-1666: Update CI build to publish github release (#32)
* update CI build to publish github release

* test release process

* update CI build to create release on core CMA JS repo

* add release script and update circleCI config to use workflows

* fix release script

* temporarily disable NPM publishing and branch filtering

* fix circle CI config

* fix config

* make tag creation optional

* update release script

* update release script to point to correct repo

* re-enable filters for master branch and NPM publish step on publish CI jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,11 +22,30 @@ jobs:
             - ./node_modules
           key: dependencies-{{ checksum "package.json" }}
 
+  publish:
+    docker:
+      - image: circleci/node:8.10
+    working_directory: ~/cumulus-message-adapter
+    steps:
+      - checkout
       - run:
-          name: Deploy
+          name: Publish release
           command: |
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              cd ~/cumulus-message-adapter
-              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
-              npm publish || echo 'npm publishing failed'
-            fi
+            GITHUB_TOKEN=${GITHUB_TOKEN} sh bin/release.sh
+      - run:
+          name: Publish to NPM
+          command: |
+            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
+            npm publish || echo 'npm publishing failed'
+
+workflows:
+  version: 2
+  build_and_publish:
+    jobs:
+      - build
+      - publish:
+          requires:
+            - build
+          filters:
+            branches:
+              only: master
